name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download modules
        run: |
          go mod tidy
          go mod download

      - name: Format
        run: |
          gofmt -w $(git ls-files '*.go')
          git diff --exit-code

      - name: Test
        run: |
          go test ./...
